export type RankingMovement = "UP" | "DOWN" | "STABLE" | "NEW";

export interface MockFighter {
  id: string;
  name: string;
  nickname: string | null;
  record: string;
  weightClass: string;
  imageUrl?: string | null;
  rankings: {
    p4p: number | null;
    division: number | null;
  };
  isChampion: boolean;
  movement: {
    p4p: RankingMovement | null;
    division: RankingMovement | null;
  };
  p4pMovementChange: number;
  divisionMovementChange: number;
}

export const fighters: MockFighter[] = [
  // ─── Heavyweight ───────────────────────────────────────────────
  {
    id: "derek-lewis",
    name: "Derek Lewis",
    imageUrl: "",
    nickname: "The Black Beast",
    record: "27-11-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: null },
    isChampion: true,
    movement: { p4p: null, division: null },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "viktor-petrov",
    name: "Viktor Petrov",
    nickname: "The Giant",
    record: "20-3-0",
    weightClass: "Heavyweight",
    rankings: { p4p: 12, division: 1 },
    isChampion: false,
    movement: { p4p: "STABLE", division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "marcus-thompson",
    name: "Marcus Thompson",
    nickname: "The Beast",
    record: "19-4-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "carlos-mendez",
    name: "Carlos Mendez",
    nickname: null,
    record: "18-2-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "alexander-okafor",
    name: "Alexander Okafor",
    nickname: "The Destroyer",
    record: "22-5-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "brock-daniels",
    name: "Brock Daniels",
    nickname: "The Hammer",
    record: "17-3-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 5 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 3,
  },
  {
    id: "tai-tuivasa",
    name: "Tai Tuivasa",
    nickname: "Bam Bam",
    record: "15-8-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 6 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "cyril-gane",
    name: "Cyril Gane",
    nickname: "Bon Gamin",
    record: "12-2-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "jairzinho-rozenstruik",
    name: "Jairzinho Rozenstruik",
    nickname: "Bigi Boy",
    record: "13-5-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "augo-sakai",
    name: "Augusto Sakai",
    nickname: null,
    record: "15-8-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 9 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "marcin-tybura",
    name: "Marcin Tybura",
    nickname: "Tybur",
    record: "23-8-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "blagoy-ivanov",
    name: "Blagoy Ivanov",
    nickname: "Baga",
    record: "19-6-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "sergey-spivak",
    name: "Sergey Spivak",
    nickname: "The Polar Bear",
    record: "16-4-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "hamdy-abdelwahab",
    name: "Hamdy Abdelwahab",
    nickname: "The Hammer",
    record: "7-0-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "NEW" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "waldo-cortes-acosta",
    name: "Waldo Cortes-Acosta",
    nickname: "Salsa Boy",
    record: "12-1-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "jacob-maloun",
    name: "Jacob Maloun",
    nickname: null,
    record: "9-2-0",
    weightClass: "Heavyweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },

  // ─── Light Heavyweight ─────────────────────────────────────────
  {
    id: "jamal-washington",
    name: "Jamal Washington",
    nickname: "The Predator",
    record: "21-2-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: 5, division: null },
    isChampion: true,
    movement: { p4p: "NEW", division: null },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "igor-kozlov",
    name: "Igor Kozlov",
    nickname: "The Siberian",
    record: "23-4-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 1 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "michael-brown",
    name: "Michael Brown",
    nickname: "The Warrior",
    record: "20-3-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "rashid-ali",
    name: "Rashid Ali",
    nickname: null,
    record: "19-5-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "daniel-fischer",
    name: "Daniel Fischer",
    nickname: "The Engine",
    record: "22-6-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "alex-pereira",
    name: "Alex Pereira",
    nickname: "Poatan",
    record: "12-2-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: 10, division: 5 },
    isChampion: false,
    movement: { p4p: "UP", division: "STABLE" },
    p4pMovementChange: 1,
    divisionMovementChange: 0,
  },
  {
    id: "jiiri-prochazka",
    name: "Jiří Procházka",
    nickname: "Denisa",
    record: "30-5-1",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 6 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "magomed-ankalaev",
    name: "Magomed Ankalaev",
    nickname: null,
    record: "18-1-1",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "nikita-kyrgios",
    name: "Nikita Krylov",
    nickname: "The Miner",
    record: "30-10-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "ryan-spann",
    name: "Ryan Spann",
    nickname: "Superman",
    record: "21-8-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 9 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "kennedy-nzechukwu",
    name: "Kennedy Nzechukwu",
    nickname: "African Savage",
    record: "12-4-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 3,
  },
  {
    id: "volkan-oezdemir",
    name: "Volkan Oezdemir",
    nickname: "No Time",
    record: "18-7-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "dustin-jacobie",
    name: "Dustin Jacoby",
    nickname: "The Hanyak",
    record: "20-8-1",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "zon-ross",
    name: "Zhalgas Zhumagulov",
    nickname: null,
    record: "14-7-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "ihuoma-achiocha",
    name: "Ihuoma Achiocha",
    nickname: null,
    record: "8-1-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "NEW" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "tomasz-ankalaev",
    name: "Tomasz Narkun",
    nickname: null,
    record: "18-5-0",
    weightClass: "Light Heavyweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },

  // ─── Middleweight ──────────────────────────────────────────────
  {
    id: "israel-adesanya",
    name: "Israel Adesanya",
    nickname: "The Last Stylebender",
    record: "24-3-0",
    weightClass: "Middleweight",
    rankings: { p4p: 8, division: null },
    isChampion: true,
    movement: { p4p: "DOWN", division: null },
    p4pMovementChange: 2,
    divisionMovementChange: 0,
  },
  {
    id: "dmitri-volkov",
    name: "Dmitri Volkov",
    nickname: "The Iron Bear",
    record: "24-2-0",
    weightClass: "Middleweight",
    rankings: { p4p: 2, division: 1 },
    isChampion: false,
    movement: { p4p: "UP", division: "UP" },
    p4pMovementChange: 1,
    divisionMovementChange: 1,
  },
  {
    id: "nathan-clarke",
    name: "Nathan Clarke",
    nickname: "The Technician",
    record: "22-3-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "ricardo-almeida",
    name: "Ricardo Almeida",
    nickname: "The Brazilian Bomb",
    record: "21-4-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "tyrone-williams",
    name: "Tyrone Williams",
    nickname: "The Problem",
    record: "18-2-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "NEW" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "sven-eriksson",
    name: "Sven Eriksson",
    nickname: null,
    record: "20-5-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 5 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "robert-whittaker",
    name: "Robert Whittaker",
    nickname: "The Reaper",
    record: "26-7-0",
    weightClass: "Middleweight",
    rankings: { p4p: 14, division: 6 },
    isChampion: false,
    movement: { p4p: "STABLE", division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "paulo-costa",
    name: "Paulo Costa",
    nickname: "The Eraser",
    record: "14-2-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "jared-cannonier",
    name: "Jared Cannonier",
    nickname: "Tha Killa Gorilla",
    record: "17-7-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "marcin-grabchak",
    name: "Marcin Grabchak",
    nickname: null,
    record: "11-3-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 9 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "dusko-todorovic",
    name: "Duško Todorović",
    nickname: "The Serbian Steel",
    record: "12-4-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "milyn-gary",
    name: "Michał Oleksiejczuk",
    nickname: "Hussar",
    record: "19-8-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "brendan-allen",
    name: "Brendan Allen",
    nickname: "All In",
    record: "23-6-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "chris-curtis",
    name: "Chris Curtis",
    nickname: "The Action Man",
    record: "31-11-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "roman-kopylov",
    name: "Roman Kopylov",
    nickname: null,
    record: "12-3-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "caio-borralho",
    name: "Caio Borralho",
    nickname: "The Natural",
    record: "16-1-0",
    weightClass: "Middleweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "NEW" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },

  // ─── Welterweight ──────────────────────────────────────────────
  {
    id: "leon-edwards",
    name: "Leon Edwards",
    nickname: "Rocky",
    record: "22-3-0",
    weightClass: "Welterweight",
    rankings: { p4p: 6, division: null },
    isChampion: true,
    movement: { p4p: "UP", division: null },
    p4pMovementChange: 1,
    divisionMovementChange: 0,
  },
  {
    id: "kenji-tanaka",
    name: "Kenji Tanaka",
    nickname: "Shadow Strike",
    record: "22-1-0",
    weightClass: "Welterweight",
    rankings: { p4p: 3, division: 1 },
    isChampion: false,
    movement: { p4p: "DOWN", division: "DOWN" },
    p4pMovementChange: 1,
    divisionMovementChange: 1,
  },
  {
    id: "ryan-omalley",
    name: "Ryan O'Malley",
    nickname: "The Irish Warrior",
    record: "23-3-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "mohammed-hassan",
    name: "Mohammed Hassan",
    nickname: "The Egyptian King",
    record: "20-2-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "jake-morrison",
    name: "Jake Morrison",
    nickname: "The Machine",
    record: "19-4-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 3,
  },
  {
    id: "lucas-silva",
    name: "Lucas Silva",
    nickname: null,
    record: "21-5-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 5 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "belal-muhammad",
    name: "Belal Muhammad",
    nickname: "Remember the Name",
    record: "23-3-0",
    weightClass: "Welterweight",
    rankings: { p4p: 11, division: 6 },
    isChampion: false,
    movement: { p4p: "STABLE", division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "colby-covington",
    name: "Colby Covington",
    nickname: "Chaos",
    record: "17-4-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "gilbert-burns",
    name: "Gilbert Burns",
    nickname: "Durinho",
    record: "22-7-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "khamzat-chimaev",
    name: "Khamzat Chimaev",
    nickname: "Borz",
    record: "13-0-0",
    weightClass: "Welterweight",
    rankings: { p4p: 9, division: 9 },
    isChampion: false,
    movement: { p4p: "UP", division: "UP" },
    p4pMovementChange: 2,
    divisionMovementChange: 2,
  },
  {
    id: "wonderboy-thompson",
    name: "Stephen Thompson",
    nickname: "Wonderboy",
    record: "17-7-1",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "vicente-luque",
    name: "Vicente Luque",
    nickname: "The Silent Assassin",
    record: "22-10-1",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "geoff-neal",
    name: "Geoff Neal",
    nickname: "Handz of Steel",
    record: "16-6-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "neil-magny",
    name: "Neil Magny",
    nickname: "The Haitian Sensation",
    record: "28-11-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "michael-pereira",
    name: "Michel Pereira",
    nickname: "Demolidor",
    record: "29-12-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "santiago-poncebnzio",
    name: "Santiago Ponzinibbio",
    nickname: "Gente Boa",
    record: "30-8-0",
    weightClass: "Welterweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },

  // ─── Lightweight ───────────────────────────────────────────────
  {
    id: "marcus-rivera",
    name: "Marcus Rivera",
    nickname: "The Storm",
    record: "26-3-0",
    weightClass: "Lightweight",
    rankings: { p4p: 1, division: null },
    isChampion: true,
    movement: { p4p: "STABLE", division: null },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "tony-ferguson",
    name: "Tony Ferguson",
    nickname: "The Ghost",
    record: "24-4-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 1 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "beneil-dariush",
    name: "Beneil Dariush",
    nickname: "Benny",
    record: "22-5-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "rafael-dos-anjos",
    name: "Rafael dos Anjos",
    nickname: "RDA",
    record: "30-13-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "arman-tsarukyan",
    name: "Arman Tsarukyan",
    nickname: "Ahalkalakets",
    record: "21-3-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "dustin-poirier",
    name: "Dustin Poirier",
    nickname: "The Diamond",
    record: "30-8-0",
    weightClass: "Lightweight",
    rankings: { p4p: 15, division: 5 },
    isChampion: false,
    movement: { p4p: "DOWN", division: "STABLE" },
    p4pMovementChange: 1,
    divisionMovementChange: 0,
  },
  {
    id: "charles-oliveira",
    name: "Charles Oliveira",
    nickname: "Do Bronx",
    record: "34-10-0",
    weightClass: "Lightweight",
    rankings: { p4p: 7, division: 6 },
    isChampion: false,
    movement: { p4p: "STABLE", division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "justin-gaethje",
    name: "Justin Gaethje",
    nickname: "The Highlight",
    record: "25-5-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "islam-makhachev",
    name: "Islam Makhachev",
    nickname: null,
    record: "25-1-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "michael-chandler",
    name: "Michael Chandler",
    nickname: "Iron",
    record: "23-8-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 9 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "paddy-pimblett",
    name: "Paddy Pimblett",
    nickname: "The Baddy",
    record: "21-3-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "NEW" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "jalin-turner",
    name: "Jalin Turner",
    nickname: "The Tarantula",
    record: "14-7-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 3,
  },
  {
    id: "damir-ismagulov",
    name: "Damir Ismagulov",
    nickname: null,
    record: "24-3-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "terence-mckinney",
    name: "Terence McKinney",
    nickname: "T-Wrecks",
    record: "15-6-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "guram-kutateladze",
    name: "Guram Kutateladze",
    nickname: null,
    record: "12-4-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "nasrat-haqparast",
    name: "Nasrat Haqparast",
    nickname: "Afghan Fury",
    record: "15-6-0",
    weightClass: "Lightweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },

  // ─── Featherweight ─────────────────────────────────────────────
  {
    id: "alex-volkanovski",
    name: "Alexander Volkanovski",
    nickname: "The Great",
    record: "26-3-0",
    weightClass: "Featherweight",
    rankings: { p4p: 13, division: null },
    isChampion: true,
    movement: { p4p: "STABLE", division: null },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "alejandro-cruz",
    name: "Alejandro Cruz",
    nickname: "El Fuego",
    record: "25-4-0",
    weightClass: "Featherweight",
    rankings: { p4p: 4, division: 1 },
    isChampion: false,
    movement: { p4p: "UP", division: "UP" },
    p4pMovementChange: 2,
    divisionMovementChange: 2,
  },
  {
    id: "max-holloway",
    name: "Max Holloway",
    nickname: "Blessed",
    record: "26-7-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "brian-ortega",
    name: "Brian Ortega",
    nickname: "T-City",
    record: "16-4-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "yair-rodriguez",
    name: "Yair Rodriguez",
    nickname: "El Pantera",
    record: "18-4-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "josh-emmett",
    name: "Josh Emmett",
    nickname: "The Funky Bantamweight",
    record: "18-4-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 5 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "arthur-lupin",
    name: "Arnold Allen",
    nickname: "Almighty",
    record: "21-2-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 6 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "korean-zombie",
    name: "Chan Sung Jung",
    nickname: "The Korean Zombie",
    record: "17-7-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "bryce-mitchell",
    name: "Bryce Mitchell",
    nickname: "Thug Nasty",
    record: "16-2-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "ilias-zorkhani",
    name: "Movsar Evloev",
    nickname: null,
    record: "18-0-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 9 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "giga-chikadze",
    name: "Giga Chikadze",
    nickname: "Ninja",
    record: "16-4-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "sung-woo-choi",
    name: "Sung Woo Choi",
    nickname: null,
    record: "11-6-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "alex-caceres",
    name: "Alex Caceres",
    nickname: "Bruce Leroy",
    record: "20-13-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "seung-woo-choi",
    name: "Choi Seung-Woo",
    nickname: null,
    record: "11-7-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "julian-arosa",
    name: "Julian Arosa",
    nickname: "Juicy J",
    record: "17-10-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "nathaniel-wood",
    name: "Nathaniel Wood",
    nickname: "The Prospect",
    record: "20-6-0",
    weightClass: "Featherweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },

  // ─── Bantamweight ──────────────────────────────────────────────
  {
    id: "aljamain-sterling",
    name: "Aljamain Sterling",
    nickname: "Funk Master",
    record: "24-4-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: null },
    isChampion: true,
    movement: { p4p: null, division: null },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "merab-dvalishvili",
    name: "Merab Dvalishvili",
    nickname: "The Machine",
    record: "20-3-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 1 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "sean-omalley",
    name: "Sean O'Malley",
    nickname: "Sugar",
    record: "18-2-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "petr-yan",
    name: "Petr Yan",
    nickname: "No Mercy",
    record: "17-5-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "jose-aldo",
    name: "Jose Aldo",
    nickname: "The King of Rio",
    record: "32-8-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "caleb-plant",
    name: "Cory Sandhagen",
    nickname: "The Sandman",
    record: "16-4-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 5 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "rob-font",
    name: "Rob Font",
    nickname: "Sonic Boom",
    record: "20-7-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 6 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "marlon-moraes",
    name: "Marlon Moraes",
    nickname: "Magic",
    record: "23-10-1",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "pedro-munhoz",
    name: "Pedro Munhoz",
    nickname: "The Young Punisher",
    record: "20-11-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "frankie-edgar",
    name: "Frankie Edgar",
    nickname: "The Answer",
    record: "24-11-1",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 9 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "rani-yahya",
    name: "Rani Yahya",
    nickname: null,
    record: "28-11-1",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "rivera-mitchell",
    name: "Raoni Barcelos",
    nickname: "Monsanto",
    record: "18-4-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "kyler-phillips",
    name: "Kyler Phillips",
    nickname: "The Matrix",
    record: "10-2-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "NEW" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "davey-grant",
    name: "Davey Grant",
    nickname: "Dangerous",
    record: "13-7-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "mingyang-zhang",
    name: "Ricky Simon",
    nickname: "The Sniper",
    record: "21-4-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "ana-seoane",
    name: "Victor Henry",
    nickname: "La Mangosta",
    record: "23-6-0",
    weightClass: "Bantamweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },

  // ─── Flyweight ─────────────────────────────────────────────────
  {
    id: "brandon-moreno",
    name: "Brandon Moreno",
    nickname: "The Assassin Baby",
    record: "21-7-2",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: null },
    isChampion: true,
    movement: { p4p: null, division: null },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "deiveson-figueiredo",
    name: "Deiveson Figueiredo",
    nickname: "Deus da Guerra",
    record: "22-3-1",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 1 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "kai-kara-france",
    name: "Kai Kara-France",
    nickname: "Don't Blink",
    record: "24-11-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 2 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "alexandre-pantoja",
    name: "Alexandre Pantoja",
    nickname: "The Cannibal",
    record: "25-5-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 3 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 3,
  },
  {
    id: "matheus-nicolau",
    name: "Matheus Nicolau",
    nickname: "Mat",
    record: "19-4-1",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 4 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "askar-mokhorev",
    name: "Askar Askarov",
    nickname: null,
    record: "14-1-1",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 5 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "tim-elliott",
    name: "Tim Elliott",
    nickname: "The Dirty Bird",
    record: "21-13-1",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 6 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "jose-torres",
    name: "Jose Torres",
    nickname: "Shorty",
    record: "11-4-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 7 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "tagir-ulanbekov",
    name: "Tagir Ulanbekov",
    nickname: "The Russian Thunder",
    record: "15-3-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 8 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 2,
  },
  {
    id: "matthew-ellsel",
    name: "Matt Schnell",
    nickname: "Danger",
    record: "16-7-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 9 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "su-mudaerji",
    name: "Su Mudaerji",
    nickname: "The Tibetan Eagle",
    record: "16-6-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 10 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "cody-durden",
    name: "Cody Durden",
    nickname: "The Gator",
    record: "16-6-1",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 11 },
    isChampion: false,
    movement: { p4p: null, division: "UP" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "jv-menezes",
    name: "Jhonata Diniz",
    nickname: null,
    record: "7-0-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 12 },
    isChampion: false,
    movement: { p4p: null, division: "NEW" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "tyson-nam",
    name: "Tyson Nam",
    nickname: "Black Zeus",
    record: "23-14-1",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 13 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
  {
    id: "zhalgas-zhumagulov",
    name: "Zhalgas Zhumagulov",
    nickname: null,
    record: "14-7-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 14 },
    isChampion: false,
    movement: { p4p: null, division: "DOWN" },
    p4pMovementChange: 0,
    divisionMovementChange: 1,
  },
  {
    id: "denys-bondar",
    name: "Denys Bondar",
    nickname: "The surgeon",
    record: "17-6-0",
    weightClass: "Flyweight",
    rankings: { p4p: null, division: 15 },
    isChampion: false,
    movement: { p4p: null, division: "STABLE" },
    p4pMovementChange: 0,
    divisionMovementChange: 0,
  },
];
