export type FightStatus = "UPCOMING" | "COMPLETED";

export type FightOutcome = "WIN" | "DRAW" | "NO_CONTEST";

export type FightMethod =
  | "KO"
  | "TKO"
  | "SUBMISSION"
  | "UNANIMOUS_DECISION"
  | "SPLIT_DECISION"
  | "MAJORITY_DECISION";

export type FightCardPosition = "MAIN_EVENT" | "CO_MAIN_EVENT" | "MAIN_CARD" | "PRELIMINARY";

export interface FightResult {
  outcome: FightOutcome;
  winnerId: string | null;
  loserId: string | null;
  method: FightMethod;
  round: number;
  time: string;
}

export interface Fight {
  id: string;
  eventId: string;
  fighter1Id: string;
  fighter2Id: string;
  weightClass: string;
  cardPosition: FightCardPosition;
  status: FightStatus;
  result: FightResult | null;
  date: string;
}

export const fights: Fight[] = [
  // ─── MMA 37 — All In ─────────────────────────────────────────
  {
    id: "rivera-vs-ferguson",
    eventId: "evt-005",
    fighter1Id: "marcus-rivera",
    fighter2Id: "tony-ferguson",
    weightClass: "Lightweight",
    cardPosition: "MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "marcus-rivera",
      loserId: "tony-ferguson",
      method: "TKO",
      round: 3,
      time: "2:11",
    },
    date: "2026-02-14",
  },
  {
    id: "orolbai-vs-tanaka",
    eventId: "evt-005",
    fighter1Id: "myktybek-orolbai",
    fighter2Id: "kenji-tanaka",
    weightClass: "Welterweight",
    cardPosition: "CO_MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "myktybek-orolbai",
      loserId: "kenji-tanaka",
      method: "SPLIT_DECISION",
      round: 5,
      time: "5:00",
    },
    date: "2026-02-14",
  },
  {
    id: "whittaker-vs-costa",
    eventId: "evt-005",
    fighter1Id: "robert-whittaker",
    fighter2Id: "paulo-costa",
    weightClass: "Middleweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "robert-whittaker",
      loserId: "paulo-costa",
      method: "TKO",
      round: 2,
      time: "3:02",
    },
    date: "2026-02-14",
  },
  {
    id: "holloway-vs-rodriguez",
    eventId: "evt-005",
    fighter1Id: "max-holloway",
    fighter2Id: "yair-rodriguez",
    weightClass: "Featherweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "max-holloway",
      loserId: "yair-rodriguez",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-02-14",
  },
  {
    id: "pereira-vs-ankalaev",
    eventId: "evt-005",
    fighter1Id: "alex-pereira",
    fighter2Id: "magomed-ankalaev",
    weightClass: "Light Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "alex-pereira",
      loserId: "magomed-ankalaev",
      method: "KO",
      round: 1,
      time: "2:58",
    },
    date: "2026-02-14",
  },
  {
    id: "cortes-acosta-vs-maloun",
    eventId: "evt-005",
    fighter1Id: "waldo-cortes-acosta",
    fighter2Id: "jacob-maloun",
    weightClass: "Heavyweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "waldo-cortes-acosta",
      loserId: "jacob-maloun",
      method: "TKO",
      round: 2,
      time: "1:40",
    },
    date: "2026-02-14",
  },
  {
    id: "edgar-vs-yahya",
    eventId: "evt-005",
    fighter1Id: "frankie-edgar",
    fighter2Id: "rani-yahya",
    weightClass: "Bantamweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "frankie-edgar",
      loserId: "rani-yahya",
      method: "SPLIT_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-02-14",
  },
  {
    id: "mudaerji-vs-durden",
    eventId: "evt-005",
    fighter1Id: "su-mudaerji",
    fighter2Id: "cody-durden",
    weightClass: "Flyweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "su-mudaerji",
      loserId: "cody-durden",
      method: "TKO",
      round: 1,
      time: "3:15",
    },
    date: "2026-02-14",
  },

  // ─── MMA 38 — Ground Zero ────────────────────────────────────
  {
    id: "moreno-vs-figueiredo-2",
    eventId: "evt-004",
    fighter1Id: "brandon-moreno",
    fighter2Id: "deiveson-figueiredo",
    weightClass: "Flyweight",
    cardPosition: "MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "brandon-moreno",
      loserId: "deiveson-figueiredo",
      method: "SUBMISSION",
      round: 4,
      time: "3:47",
    },
    date: "2026-04-04",
  },
  {
    id: "adesanya-vs-whittaker",
    eventId: "evt-004",
    fighter1Id: "israel-adesanya",
    fighter2Id: "robert-whittaker",
    weightClass: "Middleweight",
    cardPosition: "CO_MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "israel-adesanya",
      loserId: "robert-whittaker",
      method: "TKO",
      round: 3,
      time: "2:33",
    },
    date: "2026-04-04",
  },
  {
    id: "poirier-vs-gaethje",
    eventId: "evt-004",
    fighter1Id: "dustin-poirier",
    fighter2Id: "justin-gaethje",
    weightClass: "Lightweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "dustin-poirier",
      loserId: "justin-gaethje",
      method: "KO",
      round: 2,
      time: "4:38",
    },
    date: "2026-04-04",
  },
  {
    id: "thompson-vs-okafor",
    eventId: "evt-004",
    fighter1Id: "marcus-thompson",
    fighter2Id: "alexander-okafor",
    weightClass: "Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "marcus-thompson",
      loserId: "alexander-okafor",
      method: "TKO",
      round: 3,
      time: "2:04",
    },
    date: "2026-04-04",
  },
  {
    id: "chimaev-vs-burns",
    eventId: "evt-004",
    fighter1Id: "khamzat-chimaev",
    fighter2Id: "gilbert-burns",
    weightClass: "Welterweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "khamzat-chimaev",
      loserId: "gilbert-burns",
      method: "SUBMISSION",
      round: 1,
      time: "2:32",
    },
    date: "2026-04-04",
  },
  {
    id: "dvalishvili-vs-omalley",
    eventId: "evt-004",
    fighter1Id: "merab-dvalishvili",
    fighter2Id: "sean-omalley",
    weightClass: "Bantamweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "merab-dvalishvili",
      loserId: "sean-omalley",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-04-04",
  },
  {
    id: "brown-vs-ali",
    eventId: "evt-004",
    fighter1Id: "michael-brown",
    fighter2Id: "rashid-ali",
    weightClass: "Light Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "michael-brown",
      loserId: "rashid-ali",
      method: "TKO",
      round: 2,
      time: "1:28",
    },
    date: "2026-04-04",
  },
  {
    id: "kara-france-vs-nicolau",
    eventId: "evt-004",
    fighter1Id: "kai-kara-france",
    fighter2Id: "matheus-nicolau",
    weightClass: "Flyweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "kai-kara-france",
      loserId: "matheus-nicolau",
      method: "KO",
      round: 1,
      time: "1:54",
    },
    date: "2026-04-04",
  },
  {
    id: "font-vs-moraes",
    eventId: "evt-004",
    fighter1Id: "rob-font",
    fighter2Id: "marlon-moraes",
    weightClass: "Bantamweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "rob-font",
      loserId: "marlon-moraes",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-04-04",
  },
  {
    id: "abdelwahab-vs-tybura",
    eventId: "evt-004",
    fighter1Id: "hamdy-abdelwahab",
    fighter2Id: "marcin-tybura",
    weightClass: "Heavyweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "hamdy-abdelwahab",
      loserId: "marcin-tybura",
      method: "TKO",
      round: 1,
      time: "2:20",
    },
    date: "2026-04-04",
  },

  // ─── MMA 39 — Homecoming ─────────────────────────────────────
  {
    id: "rivera-vs-oliveira",
    eventId: "evt-003",
    fighter1Id: "marcus-rivera",
    fighter2Id: "charles-oliveira",
    weightClass: "Lightweight",
    cardPosition: "MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "marcus-rivera",
      loserId: "charles-oliveira",
      method: "TKO",
      round: 2,
      time: "1:32",
    },
    date: "2026-06-06",
  },
  {
    id: "gane-vs-rozenstruik",
    eventId: "evt-003",
    fighter1Id: "cyril-gane",
    fighter2Id: "jairzinho-rozenstruik",
    weightClass: "Heavyweight",
    cardPosition: "CO_MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "cyril-gane",
      loserId: "jairzinho-rozenstruik",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-06-06",
  },
  {
    id: "almeida-vs-clarke",
    eventId: "evt-003",
    fighter1Id: "ricardo-almeida",
    fighter2Id: "nathan-clarke",
    weightClass: "Middleweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "ricardo-almeida",
      loserId: "nathan-clarke",
      method: "KO",
      round: 1,
      time: "0:58",
    },
    date: "2026-06-06",
  },
  {
    id: "aldo-vs-plant",
    eventId: "evt-003",
    fighter1Id: "jose-aldo",
    fighter2Id: "caleb-plant",
    weightClass: "Bantamweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "jose-aldo",
      loserId: "caleb-plant",
      method: "SPLIT_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-06-06",
  },
  {
    id: "holloway-vs-ortega",
    eventId: "evt-003",
    fighter1Id: "max-holloway",
    fighter2Id: "brian-ortega",
    weightClass: "Featherweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "max-holloway",
      loserId: "brian-ortega",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-06-06",
  },
  {
    id: "korean-zombie-vs-lupin",
    eventId: "evt-003",
    fighter1Id: "korean-zombie",
    fighter2Id: "arthur-lupin",
    weightClass: "Featherweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "korean-zombie",
      loserId: "arthur-lupin",
      method: "SUBMISSION",
      round: 2,
      time: "3:14",
    },
    date: "2026-06-06",
  },
  {
    id: "morrison-vs-silva",
    eventId: "evt-003",
    fighter1Id: "jake-morrison",
    fighter2Id: "lucas-silva",
    weightClass: "Welterweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "jake-morrison",
      loserId: "lucas-silva",
      method: "TKO",
      round: 2,
      time: "2:59",
    },
    date: "2026-06-06",
  },
  {
    id: "pantoja-vs-mokhorev",
    eventId: "evt-003",
    fighter1Id: "alexandre-pantoja",
    fighter2Id: "askar-mokhorev",
    weightClass: "Flyweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "alexandre-pantoja",
      loserId: "askar-mokhorev",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-06-06",
  },
  {
    id: "nam-vs-zhumagulov",
    eventId: "evt-003",
    fighter1Id: "tyson-nam",
    fighter2Id: "zhalgas-zhumagulov",
    weightClass: "Flyweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "DRAW",
      winnerId: null,
      loserId: null,
      method: "MAJORITY_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-06-06",
  },
  {
    id: "pimblett-vs-ismagulov",
    eventId: "evt-003",
    fighter1Id: "paddy-pimblett",
    fighter2Id: "damir-ismagulov",
    weightClass: "Lightweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "paddy-pimblett",
      loserId: "damir-ismagulov",
      method: "SUBMISSION",
      round: 1,
      time: "3:12",
    },
    date: "2026-06-06",
  },

  // ─── MMA 40 — Collision Course ───────────────────────────────
  {
    id: "gaziev-vs-washington",
    eventId: "evt-002",
    fighter1Id: "shamil-gaziev",
    fighter2Id: "jamal-washington",
    weightClass: "Heavyweight",
    cardPosition: "MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "shamil-gaziev",
      loserId: "jamal-washington",
      method: "KO",
      round: 2,
      time: "1:58",
    },
    date: "2026-08-22",
  },
  {
    id: "chimaev-vs-muhammad",
    eventId: "evt-002",
    fighter1Id: "khamzat-chimaev",
    fighter2Id: "belal-muhammad",
    weightClass: "Welterweight",
    cardPosition: "CO_MAIN_EVENT",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "khamzat-chimaev",
      loserId: "belal-muhammad",
      method: "SUBMISSION",
      round: 2,
      time: "3:41",
    },
    date: "2026-08-22",
  },
  {
    id: "williams-vs-eriksson",
    eventId: "evt-002",
    fighter1Id: "tyrone-williams",
    fighter2Id: "sven-eriksson",
    weightClass: "Middleweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "tyrone-williams",
      loserId: "sven-eriksson",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-08-22",
  },
  {
    id: "oezdemir-vs-jacobie",
    eventId: "evt-002",
    fighter1Id: "volkan-oezdemir",
    fighter2Id: "dustin-jacobie",
    weightClass: "Light Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "volkan-oezdemir",
      loserId: "dustin-jacobie",
      method: "TKO",
      round: 2,
      time: "3:08",
    },
    date: "2026-08-22",
  },
  {
    id: "rodriguez-vs-emmett",
    eventId: "evt-002",
    fighter1Id: "yair-rodriguez",
    fighter2Id: "josh-emmett",
    weightClass: "Featherweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "yair-rodriguez",
      loserId: "josh-emmett",
      method: "KO",
      round: 2,
      time: "1:49",
    },
    date: "2026-08-22",
  },
  {
    id: "tuivasa-vs-sakai",
    eventId: "evt-002",
    fighter1Id: "tai-tuivasa",
    fighter2Id: "augo-sakai",
    weightClass: "Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "tai-tuivasa",
      loserId: "augo-sakai",
      method: "KO",
      round: 1,
      time: "2:47",
    },
    date: "2026-08-22",
  },
  {
    id: "munhoz-vs-barcelos",
    eventId: "evt-002",
    fighter1Id: "pedro-munhoz",
    fighter2Id: "rivera-mitchell",
    weightClass: "Bantamweight",
    cardPosition: "MAIN_CARD",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "pedro-munhoz",
      loserId: "rivera-mitchell",
      method: "UNANIMOUS_DECISION",
      round: 3,
      time: "5:00",
    },
    date: "2026-08-22",
  },
  {
    id: "ulanbekov-vs-torres",
    eventId: "evt-002",
    fighter1Id: "tagir-ulanbekov",
    fighter2Id: "jose-torres",
    weightClass: "Flyweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "tagir-ulanbekov",
      loserId: "jose-torres",
      method: "SUBMISSION",
      round: 2,
      time: "3:22",
    },
    date: "2026-08-22",
  },
  {
    id: "pereira-vs-ponzinibbio",
    eventId: "evt-002",
    fighter1Id: "michael-pereira",
    fighter2Id: "santiago-poncebnzio",
    weightClass: "Welterweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "WIN",
      winnerId: "michael-pereira",
      loserId: "santiago-poncebnzio",
      method: "KO",
      round: 1,
      time: "2:30",
    },
    date: "2026-08-22",
  },
  {
    id: "curtis-vs-kopylov",
    eventId: "evt-002",
    fighter1Id: "chris-curtis",
    fighter2Id: "roman-kopylov",
    weightClass: "Middleweight",
    cardPosition: "PRELIMINARY",
    status: "COMPLETED",
    result: {
      outcome: "NO_CONTEST",
      winnerId: null,
      loserId: null,
      method: "TKO",
      round: 1,
      time: "0:42",
    },
    date: "2026-08-22",
  },

  // ─── MMA — Night of Champions ────────────────────────────────
  {
    id: "adesanya-vs-volkov",
    eventId: "evt-001",
    fighter1Id: "israel-adesanya",
    fighter2Id: "dmitri-volkov",
    weightClass: "Middleweight",
    cardPosition: "MAIN_EVENT",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "sterling-vs-dvalishvili",
    eventId: "evt-001",
    fighter1Id: "aljamain-sterling",
    fighter2Id: "merab-dvalishvili",
    weightClass: "Bantamweight",
    cardPosition: "CO_MAIN_EVENT",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "rivera-vs-tsarukyan",
    eventId: "evt-001",
    fighter1Id: "marcus-rivera",
    fighter2Id: "arman-tsarukyan",
    weightClass: "Lightweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "volkanovski-vs-cruz",
    eventId: "evt-001",
    fighter1Id: "alex-volkanovski",
    fighter2Id: "alejandro-cruz",
    weightClass: "Featherweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "wonderboy-vs-luque",
    eventId: "evt-001",
    fighter1Id: "wonderboy-thompson",
    fighter2Id: "vicente-luque",
    weightClass: "Welterweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "petrov-vs-okafor",
    eventId: "evt-001",
    fighter1Id: "viktor-petrov",
    fighter2Id: "alexander-okafor",
    weightClass: "Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "ankalaev-vs-spann",
    eventId: "evt-001",
    fighter1Id: "magomed-ankalaev",
    fighter2Id: "ryan-spann",
    weightClass: "Light Heavyweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "dariush-vs-turner",
    eventId: "evt-001",
    fighter1Id: "beneil-dariush",
    fighter2Id: "jalin-turner",
    weightClass: "Lightweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "omalley-vs-font",
    eventId: "evt-001",
    fighter1Id: "sean-omalley",
    fighter2Id: "rob-font",
    weightClass: "Bantamweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },
  {
    id: "mudaerji-vs-elliott",
    eventId: "evt-001",
    fighter1Id: "su-mudaerji",
    fighter2Id: "tim-elliott",
    weightClass: "Flyweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2026-11-14",
  },

  // ─── MMA — Warpath ───────────────────────────────────────────
  {
    id: "moreno-vs-figueiredo-3",
    eventId: "evt-006",
    fighter1Id: "brandon-moreno",
    fighter2Id: "deiveson-figueiredo",
    weightClass: "Flyweight",
    cardPosition: "MAIN_EVENT",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "orolbai-vs-chimaev",
    eventId: "evt-006",
    fighter1Id: "myktybek-orolbai",
    fighter2Id: "khamzat-chimaev",
    weightClass: "Welterweight",
    cardPosition: "CO_MAIN_EVENT",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "washington-vs-kozlov",
    eventId: "evt-006",
    fighter1Id: "jamal-washington",
    fighter2Id: "igor-kozlov",
    weightClass: "Light Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "poirier-vs-chandler",
    eventId: "evt-006",
    fighter1Id: "dustin-poirier",
    fighter2Id: "michael-chandler",
    weightClass: "Lightweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "mendez-vs-daniels",
    eventId: "evt-006",
    fighter1Id: "carlos-mendez",
    fighter2Id: "brock-daniels",
    weightClass: "Heavyweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "borralho-vs-allen",
    eventId: "evt-006",
    fighter1Id: "caio-borralho",
    fighter2Id: "brendan-allen",
    weightClass: "Middleweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "zorkhani-vs-chikadze",
    eventId: "evt-006",
    fighter1Id: "ilias-zorkhani",
    fighter2Id: "giga-chikadze",
    weightClass: "Featherweight",
    cardPosition: "MAIN_CARD",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "yan-vs-aldo",
    eventId: "evt-006",
    fighter1Id: "petr-yan",
    fighter2Id: "jose-aldo",
    weightClass: "Bantamweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "pantoja-vs-kara-france",
    eventId: "evt-006",
    fighter1Id: "alexandre-pantoja",
    fighter2Id: "kai-kara-france",
    weightClass: "Flyweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "covington-vs-neal",
    eventId: "evt-006",
    fighter1Id: "colby-covington",
    fighter2Id: "geoff-neal",
    weightClass: "Welterweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "pimblett-vs-turner",
    eventId: "evt-006",
    fighter1Id: "paddy-pimblett",
    fighter2Id: "jalin-turner",
    weightClass: "Lightweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
  {
    id: "spivak-vs-cortes-acosta",
    eventId: "evt-006",
    fighter1Id: "sergey-spivak",
    fighter2Id: "waldo-cortes-acosta",
    weightClass: "Heavyweight",
    cardPosition: "PRELIMINARY",
    status: "UPCOMING",
    result: null,
    date: "2027-02-20",
  },
];